language: node_js

node_js:
  - "8"
  - "10"

branches:
  only:
    - master

cache: yarn

env:
  global:
  # SLACK
  - secure: "iD6GcAYcBUb0wiVplvq3wV7rTlXJ3BVOJxqAexiUfIPul198Rh+SJ6ttbRGkKi1J4FvrWTzxJo+KAWGWYyYI78LCxtUym4Z5nqfe02MQGlhOa6vVLJQ8ILqCMUuO8/8u49keqM09nTwM4jud9QAwKe9KKWNBSSt6f4Sxk8VVpXfFvyrkb3OKVdjFSPj45y8I+6TdjOreKMIhyAdAzLAsptI3SfLcRwk/+BI5m67tJrHe9OU8dcx7VUIpxpfXzHoErResR349q4pN1MPlgmwjUfFOQzo7TyLZhXr2v/uIWY3uM80WBw+xQm6PuA0kaGsxj13xIciG11NVMKdERDD7IvzJLMZa1/1gKUBWDZI/q86p6lvvBC3TMx5dmiZovxpLy3sOooilamcIhunOB4X1FQpHt6zAHjI3+2DuGnqV4Qsn4cDOW5XqmeJzXnUDoPuYA6800kj/EXr6n2OcFrwexOmy8Mn5G1jqsHYnChto5WXFUua2uoj7rDKPL6Nigard6t349VLTo40DZ3ygOGIj7lgFk1j9ik/zGX9sOSHCS0LIsdeB1HWydlETWAvX7EMIprhd0q7v9E2kYrmibwNJvOk6CIbwvORpYX+CzZhrdunbDSoeW4RJJWjFCfq7UQEN7pAsFaZug990WSJvefqrh2RvEJImP86rNtu7VeTj6BM="
  # NPM
  - secure: "K5UvB/luwXipnGeSaoEnqTiN2IKpXNPwu8v3vPd6DFojINKYmeuDAN3622UgV8mQ24q3ekNR9VUd/Q9aSCdRNuvNfxnQxm66l2p6caO7eIrTaNDr3PM1bMeauxNIgrcxmSzcs7/b5syfEKE+YEHsJ4LE/tiWxcqcZWvjRmYaD4Xpo7xk7i7Eh3MneCxz1MesHD8l+qe3eRghhSqcq9hGuP/gwugtudHZmVYhp/JnzVS6UihpnjD/LROIW5QKSvbllGusB+it76hgjpOop3WQsd73RQkdqUybpCbqg4SAKF4zSYfZBx0boWPGI189zjbmOkI5/HIrQpCjNqNnbM9RoCPBA8m/UB07s42w+uBoVNZHozSU62Acj9zV0wI9t755/6+RWM7XQJ/V2n2iEND7oXbLT2vM3eXZsKodey/i1is8ruo5IWkcARHoPoeENmx1PQu6mF5sjCwPaXswGKwRuZjNvkiAuEeqAgOKMAS5LpowXRX8RZT+ai5CIXYrAEbPXou1X1/tRPM0K+gGElGP/GNiugN/VChcN6KGPTB+jxawtOpJ/wWxcsLFcDK2Le41M9jwdT8RHoRwEvxCUdyTnpbs9wPp70piG2seLg+JVBIRwPNu9wZrTvw6/ZU46qt6nYc0MqPwiI0jopdIYgsZAjFk0whIR7/g/iS60yJ93XI="
  # GITHUB
  - secure: "jJBF3HWN+7q3RI3KpxJZdmrD5en+Jrgdv5/8uuJqKvCwY3JAR3tcKs8qR+4m1M2toE6eqMhgV0128x2aggr/YHu5yhW6NHgu8wmO7cvXsMMcuK3qhNAUV4PSYMsCk5cJ5QVqGsajXYc3jDxDLVTNF8yAhsWLrMceYD8HsVeayjNHhrAP352TVqDSY+FRU8TvKD3qHPB2mhBVfYh/jyzsCD/2lOaxnvn9hwTVMS9sLMk0S1XN6tl1lsOrwANpIFVqtIsJDUZu/U0VdvfHiSYVh0PdhgSigB2IM7DRRd3gD53ovAIWlyxnNsOFDFdzfXa3IfTxIbcSgKVMQH9RtciO0R5xu6WjsmT4xyNkptceqJl5JK4j74tKa9JHWxwdgoMknBVtBV/bFm98CEbcqh9WwYVbIoyhKgnNhAWtUpJRxd0OFRiKjqwQ871R6MPU56uavyF6fu7YvYjRW6uA6HstK1QBcO30guyRj1xqynAvZpAYw8ygczKTmSQfFr9k2Qqd31mQO5CnumjM9DNb10kiHVirQgcvRZqhnH2x6yBDMNoJGmQqXYSp6FVN1lFsBSecTi3BHcWl91Uaatr9mFJOD6wJ5+v3WbkZL6YIFQ4HeBIbN8MT3Pf30JLmlWEY9vNWFQVcmumZdiYHsZ4O2fO3vWVTtzOlhZPsU+fcXA087AE="

before_install:
  - echo "//registry.npmjs.com/:_authToken=\${NPM_TOKEN}" > .npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - make run

after_script:
  - ioffice-travis-slack
